---
title: "The Dark Side of Personality"
output: 
  html_document:
    toc: TRUE
    toc_depth: 1
    toc_float: TRUE
    number_sections: TRUE
---

***

<div class="column-left">

**Instructor** 

Name: Cameron S. Kay 

Pronouns: he/him/his

Email: ckay@uoregon.edu

Office Hours: By appointment

</div>

<div class="column-right">

**Class Materials** 

All required readings will be posted to the Modules tab on [canvas](www.canvas.com).   
    
</div>

<div class="column-center">

**Class Information**

Term: Spring, 2020

Location: Canvas

Time: Asynchronous

</div>

<br />

***

# Course Description

This course aims to complement existing courses on personality by taking an in-depth look at a number of ostensibly negative personality traits. The first half of the course will be spent exploring Machiavellianism, narcissism, psychopathy, and sadism. We will discuss these traits in terms of their history, structure, measurement, and potential etiology. The second half of the course will be dedicated to examining negative personality traits with respect to personality disorders, criminality, the workplace, morality, and internet behaviours. This course is not intended as a comprehensive review of negative personality traits. Rather, I have chosen papers that I believe provide an accessible introduction to the respective topics. Hopefully, they will inspire you to engage in future self-directed study.  

<br />

# Course Format

Because of COVID-19, we will, unfortunately, be unable to meet for in-person discussions. Although this is unfortunate, it is, without a doubt, the correct decision. 

I've reworked the course format to hopefully make the switch as minimally disruptive to the stated objectives of the course as possible. The restructured course is now as follows:

* By the end of the first week (Sunday, April 4th, at 11:59 pm), I will ask you to complete a [precourse exercise](#pce) on Canvas. The [precourse exercise](#pce) assesses your familiarity with the topics to be covered in the course and assesses certain aspects of your psychological and behavioural profiles.    
* Every Wednesday by 5:00 pm, I would like you to post a [reading response](#rr) responding to one of the week's readings on Canvas Discussions.
* Every Thursday, I will post a recorded lecture to Canvas to provide background on the readings and a summary of the current state of the field.
* Between the lecture being posted on Thursday and Sunday at 5:00 pm, you will have to [participate](#participation) in an online discussion by commenting on the [reading response](#rr) of at least one other student on Canvas Discussions.
* By 11:59 pm on Friday of Week 10, you will upload a [profile paper](#pp) to Canvas. 
  
<br />

# Learning Objectives

* Identify and describe negative personality traits at the level of the concept, construct, and subconstruct.
* Explore relations among the traits.
* Describe a current theory for the presence of these traits in humans.
* Distinguish between subclinical and clinical variations of these traits.
* Examine the relationship between morality and each of the traits. 
* Apply an understanding of the traits to relationship and occupational contexts.
* Develop skills in consuming and critically evaluating research and measurement methods that can be applied to topics beyond the scope of the course.

<br />

# Estimated Student Workload

According to federal policy, a single course credit is equivalent to 30 hours of real student work. This includes (a) time spent physically in the classroom and (b) time spent outside of the classroom working on classwork. A two-credit course, such as this, expects 60 hours of real student work with 20 of those hours spent in the classroom and 40 of those hours spent working outside of the classroom. We will, however, not be meeting in-person this term. One solution would be to increase the number of readings and assignments to make up the difference. A second solution (and the solution I've chosen to go with) is to simply encourage you to spend more time with the readings and the assignments than you would have otherwise. Over the current course, it is expected that you will spend approximately 10 hours listening to lectures; 40 hours reading course materials, preparing reading responses, and commenting on reading responses (4/hr per week); and 10 hours writing the profile paper.

<br />

# Assignments and Engagement

| Component                                 | Percent of Grade       | Date Due                                                          |
|-------------------------------------------|------------------------|-------------------------------------------------------------------|
| Precourse Exercise                        | 6%                     | Completed by 11:59 pm on Sunday of Week 1 (04/05/2020).           |
| Reading Responses                         | 36%                    | Posted to Canvas Discussions by 5:00 pm every Wednesday.          |
| Participation (Reading Response Comment)  | 18%                    | Posted to Canvas Discussions by 5:00 pm every Sunday.             |
| Profile Paper                             | 40%                    | Uploaded to Canvas by 11:59 pm on Friday of Week 10 (06/05/2020). |
|                                           |                        |                                                                   |

## Precourse Exercise {#pce}

+ Percent of total grade: 6.00%
+ Due: Completed by Sunday of Week 1 (04/05/2020).
+ Requirements: The *Precourse Exercise* assesses your preconceptions regarding the content to be covered in the course. It will also contain scales measuring aspects of your personality and behavioural tendencies. This data may be presented to the rest of the class to illustrate key course concepts. The data will be collected using an anonymous link so that I (and the rest of the class) will be unable to link your answers to you. Still, you are free to skip any question that makes you feel uncomfortable. I will grade the survey on a “pass versus no-pass” basis.
+ *Note.* For students joining the class after Sunday of Week 1, send me an email before the end of the second week of classes. I will assign you an alternative exercise of comparable length to the precourse exercise.

## Reading Responses {#rr}

+ Percent of total grade: 36.00%
+ Due: Posted to Canvas Discussions by 5:00 pm every Wednesday.
+ Requirements: The night before each class, students will submit responses to one of the assigned readings on Canvas Discussions. These reading responses will be viewable by other students in the class. The purpose of the responses is to prepare students for a productive discussion on Canvas. You are free to comment on any aspects of the paper you wish: You could discuss an idea you think is important, critique an idea that you think is questionable, or include an anecdote that relates to a finding. It is completely up to you! The responses are evaluated on the basis of perceived effort and thoroughness. The responses **will not** be evaluated on the basis of spelling, grammar, and compositional structure, as long as they are generally understandable (i.e., I can't grade something I can't understand). The responses should not merely be summaries of the papers, nor should they rely on long quotes. I advise you to aim for at least 150 words.

## Participation {#participation}

+ Percent of total grade: 18.00%
+ Due: Posted to Canvas Discussions by 5:00 pm every Sunday.
+ Requirements: At any time between the lecture video being posted on Thursday and Sunday at 5:00 pm, students should log onto Canvas and comment on the [reading response](#rr) of at least one other student (although you are certainly welcome to comment on more than one). This comment must be substantive (i.e., you must critically engage with the response using knowledge gained through the given week's readings and the lecture). As with the [reading responses](#rr), I will grade the comments on the basis of perceived effort and thoroughness. I would aim for at least 60 words. 
+ *Note.* Making your writing public---especially on a topic that you may not be familiar with---can be daunting. These comments are meant to help us learn from each other. If I feel your comment is negative or inappropriate, I will delete it and assign you a score of zero for the week. Constructive feedback is okay, but remember that we are all still learning. 

## Profile Paper {#pp}

+ Percent of total grade: 40.00%
+ Due: Uploaded to Canvas by 11:59pm on Friday of Week 10 (06/05/2020).
+ Requirements: The Profile Paper aims to assess your ability to critically and creatively apply course content to describe the personality of a fictional character of your choosing. I suggest that you choose either a villain (e.g., Wicked Witch of the West; Emperor Palpatine; Dolores Umbridge) or an antihero (e.g., Harley Quinn; Walter White; Selina Meyer) to ensure your character of interest exhibits sufficient levels of the dark personality traits. The paper is to be 8-12 double-spaced pages in length, excluding the title page and references, with Times New Roman 12-point font and 2.54cm margins. You must include at least 8 references to peer-reviewed journal articles.
+ *Note.* This assignment was inspired by a similar assignment designed by Sunaina Assanand (2017) at the University of British Columbia.

<br />

# Percentage to Letter Grades

| Letter | Percent | Letter | Percent | Letter | Percent | Letter | Percent | Letter | Percent |
|--------|---------|--------|---------|--------|---------|--------|---------|--------|---------|
| A+     | 97-100% | B+     | 87-89%  | C+     | 77-79%  | D+     | 67-69%  | F      | < 60%   |
| A      | 93-96%  | B      | 83-86%  | C      | 73-76%  | D      | 63-66%  | P*     | >= 70%  |
| A-     | 90-92%  | B-     | 80-82%  | C-     | 70-72%  | D-     | 60-62%  | N*     | <  70%  |
|        |         |        |         |        |         |        |         |        |         |

I expect the average grade received for this course to be ~85% with a standard deviation of 8. To avoid potential grade inflation and to maintain fairness across different courses at the University of Oregon, I reserve the right to scale grades to conform to this distribution.

<!--
```{r}
set.seed(1)

hist(rnorm(25, 85, 8), breaks = seq(60, 110, 3))
```
-->

<br />

# Course Policies and Acknowledgements

## Classroom Etiquette

I ask that you help foster a (virtual) classroom that is free from distractions, respectful of others, and inclusive. If I feel that you have failed to support this effort in any way, I will ask you to leave the (virtual) classroom. If you feel that someone else has failed to support these efforts, I ask that you contact me (ckay@uoregon.edu) or, if the issue is serious, the Office of the Dean of Students (541-346-3216). 

<!--
## Technology Use

Note-taking by hand---even for those who do not have a diagnosed learning disability---can often be difficult for students who write slower than their peers. Laptops and cellphones can also be a helpful way to organize your thoughts and to look-up course concepts. I do allow the use of cellphones and laptops in the classroom, but users of these devices should sit near the walls so as to avoid the bright screens distracting other students. I do also reserve the right to prohibit laptop and cellphone use for anyone who distracts other students.
-->

## Reading policy

You are required to do all of the assigned readings before the lecture is posted. Failure to do so will not be assessed directly but will be assessed indirectly through your reading response and participation grades.
	
## Late Assignments 

Late exercises and papers will be docked 25% for each day that they are late. This means, if you turn in the profile paper two days late, you would receive a maximum of 50% for your work. Students may request extensions, but these requests are unlikely to be successful.

## Email Policy

I tend to check my email twice per day: Once in the morning and once in the evening. However, if you send an email at 7:00 am on the day of class, I may not respond to it before the class. Please allow at least 24 hours for a response. If I do not respond within 24 hours, it is safe to assume that I did not receive your email, it was erroneously archived, or it was sent to my spam folder. You should resend the email.

## Accessibility

If you require accommodations due to a documented disability, please contact me as soon as possible. You will also need to use the [Accessible Education Center portal](https://aec.uoregon.edu/content/using-aec-connect) to have a notification letter sent to me. If you do not know how to use the portal, please phone 541-346-1155 or email uoaec@uoregon.edu.

## Academic Integrity 

Cheating or plagiarism will result in a grade of F for the course, and UO’s student conduct coordinator will be notified. Cheating includes, but is not necessarily limited to, providing or accepting information during tests. Plagiarism includes, but is not necessarily limited to, quoting or paraphrasing someone else’s ideas without acknowledging the source. If you are unsure of whether a particular behaviour counts as cheating or plagiarism, you should contact me (ckay@uoregon.edu) or the Office of the Dean of Students (phone: 541-346-3216; email: conduct@uoregon.edu).

## Land Acknowledgement

We acknowledge that the University of Oregon is situated on Kalapuya Iliʔi---the ancestral territory of the Kalapuya people. As a University, we should honour the traditional stewards of this land and pay respect to the elders, both past and present.
